'use client';

import { useState, useEffect, useCallback } from 'react';

type Asset = {
  id: string;
  url: string;
  format: string;
  tool: string;
  prompt: string | null;
  createdAt: string;
  width: number | null;
  height: number | null;
};

const TOOL_LABELS: Record<string, string> = {
  generate: 'Generate',
  animate: 'Animate',
  rotate: 'Rotate',
  inpaint: 'Inpaint',
  scene: 'Scene',
};

const TOOL_COLORS: Record<string, string> = {
  generate: 'bg-violet-500/10 text-violet-400',
  animate: 'bg-pink-500/10 text-pink-400',
  rotate: 'bg-blue-500/10 text-blue-400',
  inpaint: 'bg-emerald-500/10 text-emerald-400',
  scene: 'bg-amber-500/10 text-amber-400',
};

export default function GalleryPage() {
  const [assets, setAssets] = useState<Asset[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState('');
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);

  const fetchGallery = useCallback(async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams({ page: String(page), limit: '24' });
      if (filter) params.set('tool', filter);
      const res = await fetch(`/api/gallery?${params}`);
      const data = await res.json();
      setAssets(data.assets ?? []);
      setTotalPages(data.pagination?.pages ?? 1);
    } finally {
      setLoading(false);
    }
  }, [page, filter]);

  useEffect(() => { fetchGallery(); }, [fetchGallery]);

  return (
    <div className="min-h-screen bg-slate-950">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-white mb-2">Community Gallery</h1>
          <p className="text-slate-400">Pixel art generated by the WokGen community.</p>
        </div>

        {/* Filters */}
        <div className="flex flex-wrap gap-2 mb-8">
          {['', 'generate', 'animate', 'rotate', 'inpaint', 'scene'].map((t) => (
            <button
              key={t}
              onClick={() => { setFilter(t); setPage(1); }}
              className={`px-4 py-1.5 rounded-full text-sm font-medium transition-colors ${
                filter === t
                  ? 'bg-violet-600 text-white'
                  : 'bg-slate-800 text-slate-400 hover:text-white'
              }`}
            >
              {t ? TOOL_LABELS[t] : 'All'}
            </button>
          ))}
        </div>

        {/* Grid */}
        {loading ? (
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4">
            {Array.from({ length: 24 }).map((_, i) => (
              <div key={i} className="aspect-square bg-slate-900 rounded-xl animate-pulse" />
            ))}
          </div>
        ) : assets.length === 0 ? (
          <div className="text-center py-24">
            <div className="text-6xl mb-4 opacity-20">✦</div>
            <p className="text-slate-500">No public assets yet.</p>
            <a href="/studio" className="mt-4 inline-block text-violet-400 hover:text-violet-300 text-sm">
              Generate something →
            </a>
          </div>
        ) : (
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4">
            {assets.map((asset) => (
              <div key={asset.id} className="group relative bg-slate-900 rounded-xl border border-slate-800 overflow-hidden hover:border-slate-600 transition-all">
                <div
                  className="absolute inset-0 opacity-20"
                  style={{
                    backgroundImage: 'linear-gradient(45deg, #1e293b 25%, transparent 25%), linear-gradient(-45deg, #1e293b 25%, transparent 25%), linear-gradient(45deg, transparent 75%, #1e293b 75%), linear-gradient(-45deg, transparent 75%, #1e293b 75%)',
                    backgroundSize: '8px 8px',
                    backgroundPosition: '0 0, 0 4px, 4px -4px, -4px 0px',
                  }}
                />
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={asset.url}
                  alt={asset.prompt ?? 'Generated pixel art'}
                  className="relative w-full aspect-square object-contain p-2"
                  style={{ imageRendering: 'pixelated' }}
                />
                <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/80 to-transparent p-2 opacity-0 group-hover:opacity-100 transition-opacity">
                  <span className={`text-xs px-1.5 py-0.5 rounded font-medium ${TOOL_COLORS[asset.tool] ?? 'bg-slate-700 text-slate-300'}`}>
                    {TOOL_LABELS[asset.tool] ?? asset.tool}
                  </span>
                  {asset.prompt && (
                    <p className="text-white text-xs mt-1 line-clamp-2 leading-tight">{asset.prompt}</p>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Pagination */}
        {totalPages > 1 && (
          <div className="flex justify-center gap-2 mt-12">
            <button
              onClick={() => setPage((p) => Math.max(1, p - 1))}
              disabled={page === 1}
              className="px-4 py-2 bg-slate-800 text-slate-300 rounded-lg disabled:opacity-40 hover:bg-slate-700 transition-colors text-sm"
            >
              ← Prev
            </button>
            <span className="px-4 py-2 text-slate-400 text-sm">
              {page} / {totalPages}
            </span>
            <button
              onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
              disabled={page === totalPages}
              className="px-4 py-2 bg-slate-800 text-slate-300 rounded-lg disabled:opacity-40 hover:bg-slate-700 transition-colors text-sm"
            >
              Next →
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
