// Tool registry — all tool definitions for the /tools hub
// This is a separate file so page.tsx can only export the default component.

export interface ToolDef {
  id: string;
  label: string;
  description: string;
  href: string;
  tags: ToolTag[];
  icon: string;
  status: 'live' | 'beta' | 'soon';
  clientOnly?: boolean;
  isNew?: boolean;
}

export type ToolTag =
  | 'image' | 'design' | 'dev' | 'gamedev' | 'pdf'
  | 'text' | 'crypto' | 'audio' | 'collab' | 'misc';

export const TAG_LABELS: Record<ToolTag, string> = {
  image:   'Image',
  design:  'Design',
  dev:     'Dev',
  gamedev: 'Game Dev',
  pdf:     'PDF',
  text:    'Text',
  crypto:  '₿ Crypto',
  audio:   'Audio',
  collab:  'Collab',
  misc:    'Misc',
};

export const TOOLS: ToolDef[] = [
  // ── IMAGE ────────────────────────────────────────────────────────────────
  {
    id: 'background-remover',
    label: 'Background Remover',
    description: 'Remove backgrounds from images instantly. Runs entirely in your browser — no upload required.',
    href: '/tools/background-remover',
    tags: ['image'],
    icon: 'BG',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'image-converter',
    label: 'Image Converter',
    description: 'Convert between PNG, JPG, WebP, GIF, and AVIF. Batch up to 10 files at once.',
    href: '/tools/image-converter',
    tags: ['image'],
    icon: 'CV',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'image-compress',
    label: 'Image Compressor',
    description: 'Compress images with a quality slider. Live before/after size comparison.',
    href: '/tools/image-compress',
    tags: ['image'],
    icon: 'CMP',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'image-resize',
    label: 'Image Resizer',
    description: 'Resize and crop images. Social media presets for every platform. Batch mode.',
    href: '/tools/image-resize',
    tags: ['image'],
    icon: 'RSZ',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'color-palette',
    label: 'Color Palette Extractor',
    description: 'Extract dominant colors from any image. Export as CSS variables, JSON, or Tailwind config.',
    href: '/tools/color-palette',
    tags: ['image', 'design'],
    icon: 'CLR',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'social-resize',
    label: 'Social Media Resizer',
    description: 'Upload once, export for every platform: Instagram, Twitter, YouTube, TikTok, LinkedIn, OG.',
    href: '/tools/social-resize',
    tags: ['image'],
    icon: 'SOC',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'sprite-packer',
    label: 'Sprite Sheet Packer',
    description: 'Pack multiple PNGs into a sprite atlas. Exports PNG + JSON manifest with texture coordinates.',
    href: '/tools/sprite-packer',
    tags: ['image', 'gamedev'],
    icon: 'SPR',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'pixel-editor',
    label: 'Pixel Art Editor',
    description: 'Quick browser-based pixel art editor. Grid canvas, pencil, fill, eraser, palette. Export PNG.',
    href: '/tools/pixel-editor',
    tags: ['image', 'gamedev'],
    icon: 'PIX',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'favicon',
    label: 'Favicon Generator',
    description: 'Upload any image → favicon.ico (16/32/48/64px), PNG variants, apple-touch-icon. ZIP download.',
    href: '/tools/favicon',
    tags: ['image', 'dev'],
    icon: 'FAV',
    status: 'live',
    clientOnly: true,
  },
  // ── DESIGN ───────────────────────────────────────────────────────────────
  {
    id: 'css-generator',
    label: 'CSS Generator Suite',
    description: 'Gradient, glassmorphism, box shadow, border radius, and animation builders with live preview.',
    href: '/tools/css-generator',
    tags: ['design', 'dev'],
    icon: 'CSS',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'color-tools',
    label: 'Color Utilities',
    description: 'Hex/RGB/HSL/OKLCH converter, WCAG contrast checker, color harmonies, and palette generator.',
    href: '/tools/color-tools',
    tags: ['design', 'dev'],
    icon: 'CUTIL',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'og-preview',
    label: 'Open Graph Preview',
    description: 'Preview how your link appears on Twitter/X, Facebook, LinkedIn, Discord, and Slack.',
    href: '/tools/og-preview',
    tags: ['design', 'dev'],
    icon: 'OG',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'mockup',
    label: 'Mockup Generator',
    description: 'Drop your screenshot into device frames: MacBook, iPhone, iPad, Android, Browser window.',
    href: '/tools/mockup',
    tags: ['design'],
    icon: 'MCK',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'font-pairer',
    label: 'Font Pairer',
    description: 'Browse Google Fonts, pick heading + body pairs. Live preview with your own text.',
    href: '/tools/font-pairer',
    tags: ['design'],
    icon: 'FNT',
    status: 'live',
    clientOnly: true,
  },
  // ── DEV ──────────────────────────────────────────────────────────────────
  {
    id: 'json-tools',
    label: 'JSON Toolkit',
    description: 'Format, validate, minify, diff, and convert JSON. JSON path queries. All client-side.',
    href: '/tools/json-tools',
    tags: ['dev'],
    icon: '{ }',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'regex',
    label: 'Regex Tester',
    description: 'Live match highlighting, group captures, pattern explanation, and a library of common patterns.',
    href: '/tools/regex',
    tags: ['dev'],
    icon: 'DIF',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'encode-decode',
    label: 'Encode / Decode',
    description: 'Base64, URL encoding, HTML entities, Unicode escape, JWT decoder, Morse code, ROT13.',
    href: '/tools/encode-decode',
    tags: ['dev'],
    icon: 'ENC',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'hash',
    label: 'Hash Generator',
    description: 'Generate MD5, SHA-1, SHA-256, SHA-512, SHA-3 for text or files. File checksum verifier.',
    href: '/tools/hash',
    tags: ['dev'],
    icon: '#',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'generators',
    label: 'Developer Generators',
    description: 'UUID v4/v7, password generator with entropy meter, Lorem ipsum, CRON builder, timestamp converter, text diff.',
    href: '/tools/generators',
    tags: ['dev'],
    icon: 'GEN',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'markdown',
    label: 'Markdown Editor',
    description: 'Split-pane editor with live preview, GFM support, table of contents, and export to HTML.',
    href: '/tools/markdown',
    tags: ['dev', 'text'],
    icon: 'MD',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'csv-tools',
    label: 'CSV / Data Tools',
    description: 'Convert CSV ↔ JSON ↔ YAML. Table viewer with sort and filter. Column statistics.',
    href: '/tools/csv-tools',
    tags: ['dev'],
    icon: 'CSV',
    status: 'live',
    clientOnly: true,
  },
  // ── GAME DEV ─────────────────────────────────────────────────────────────
  {
    id: 'tilemap',
    label: 'Tilemap Generator',
    description: 'Upload a tileset, paint tiles on a grid, export Tiled-compatible JSON. Game dev essential.',
    href: '/tools/tilemap',
    tags: ['gamedev'],
    icon: 'MAP',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'asset-manifest',
    label: 'Asset Manifest Builder',
    description: 'Drop a folder of assets, get a Phaser/Pixi/Unity-compatible manifest JSON instantly.',
    href: '/tools/asset-manifest',
    tags: ['gamedev', 'dev'],
    icon: 'JSN',
    status: 'live',
    clientOnly: true,
  },
  // ── PDF ──────────────────────────────────────────────────────────────────
  {
    id: 'pdf',
    label: 'PDF Toolkit',
    description: 'Merge PDFs, extract pages, convert to images, add watermarks, compress. All browser-side.',
    href: '/tools/pdf',
    tags: ['pdf'],
    icon: 'PDF',
    status: 'live',
    clientOnly: true,
  },
  // ── TEXT ─────────────────────────────────────────────────────────────────
  {
    id: 'text-tools',
    label: 'Text Utilities',
    description: 'Word counter, 7 case formats, slug generator, sort/dedup lines, extract URLs and emails.',
    href: '/tools/text-tools',
    tags: ['text'],
    icon: 'TXT',
    status: 'live',
    clientOnly: true,
  },
  // ── CRYPTO ───────────────────────────────────────────────────────────────
  {
    id: 'crypto-tools',
    label: 'Crypto / Web3 Utils',
    description: 'QR code generator, wallet address validator (BTC/ETH/SOL), ENS lookup, hex/dec/bin converter.',
    href: '/tools/crypto-tools',
    tags: ['crypto'],
    icon: '₿',
    status: 'live',
    clientOnly: true,
  },
  // ── AUDIO ────────────────────────────────────────────────────────────────
  {
    id: 'audio-tools',
    label: 'Audio Utilities',
    description: 'Visualize audio waveforms, view file metadata, and create animated GIFs from image sequences.',
    href: '/tools/audio-tools',
    tags: ['audio'],
    icon: 'AUD',
    status: 'live',
    clientOnly: true,
  },
  // ── COLLAB ───────────────────────────────────────────────────────────────
  {
    id: 'whiteboard',
    label: 'Infinite Whiteboard',
    description: 'Open-source infinite canvas (tldraw). Shapes, arrows, sticky notes, freehand. Auto-saves locally.',
    href: '/tools/whiteboard',
    tags: ['collab'],
    icon: 'WB',
    status: 'live',
    clientOnly: true,
  },
  {
    id: 'snippets',
    label: 'Code Snippet Manager',
    description: 'Save, tag, and search code snippets. Syntax highlighting for 50+ languages. Public or private.',
    href: '/tools/snippets',
    tags: ['dev', 'collab'],
    icon: 'SNP',
    status: 'live',
    clientOnly: false,
  },
  // ── NEW TOOLS ────────────────────────────────────────────────────────────
  {
    id: 'color-extractor',
    label: 'Color Extractor',
    description: 'Extract a color palette from any image. Runs k-means clustering client-side — no upload.',
    href: '/tools/color-extractor',
    tags: ['image', 'design'],
    icon: 'CE',
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'type-scale',
    label: 'Type Scale',
    description: 'Generate a visual typography scale from a base size and ratio. Export as CSS variables.',
    href: '/tools/type-scale',
    tags: ['design', 'dev'],
    icon: 'TYP',
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'gradient-generator',
    label: 'Gradient Generator',
    description: 'Build CSS gradients (linear, radial, conic) with live preview. Adjust stops and copy CSS.',
    href: '/tools/gradient-generator',
    tags: ['design', 'dev'],
    icon: 'FAV',
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'border-radius',
    label: 'Border Radius Visualizer',
    description: 'Interactive border-radius builder with per-corner sliders. Live preview and copy CSS.',
    href: '/tools/border-radius',
    tags: ['design', 'dev'],
    icon: 'BR',
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'image-diff',
    label: 'Image Diff',
    description: 'Compare two images side-by-side with an interactive drag slider. Great for before/after.',
    href: '/tools/image-diff',
    tags: ['image', 'design'],
    icon: 'DIF',
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'readme-generator',
    label: 'README Generator',
    description: 'Fill in project details and generate a professional README.md instantly.',
    href: '/tools/readme-generator',
    tags: ['dev'],
    icon: 'MD',
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'jwt-debugger',
    label: 'JWT Debugger',
    description: 'Decode and inspect JWT tokens. View header, payload, and expiry. Entirely client-side.',
    href: '/tools/jwt-debugger',
    tags: ['dev', 'crypto'],
    icon: 'JWT',
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'base-converter',
    label: 'Base Converter',
    description: 'Convert numbers between binary, octal, decimal, and hexadecimal.',
    href: '/tools/base-converter',
    tags: ['dev'],
    icon: '0x',
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'tech-badges',
    label: 'Tech Stack Badge Builder',
    description: 'Select technologies and generate shields.io badge markdown for your README.',
    href: '/tools/tech-badges',
    tags: ['dev'],
    icon: 'BD',
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'media-downloader',
    label: 'Media Downloader',
    description: 'Download images, audio, and video from any public URL. Supports direct file links and HTML pages.',
    href: '/tools/media-downloader',
    icon: 'DL',
    tags: ['image', 'audio', 'dev'],
    status: 'live',
    isNew: true,
  },
  {
    id: 'link-scraper',
    label: 'Link Scraper',
    description: 'Extract all links, images, and metadata from any public webpage. Export as JSON or copy to clipboard.',
    href: '/tools/link-scraper',
    icon: 'SCR',
    tags: ['dev'],
    status: 'live',
    isNew: true,
  },
  {
    id: 'diff',
    label: 'Text Diff',
    description: 'Compare two texts side by side. Lines added, removed, and unchanged are highlighted.',
    href: '/tools/diff',
    icon: 'DIFF',
    tags: ['dev'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'cron-builder',
    label: 'Cron Builder',
    description: 'Build and validate cron expressions. Human-readable description and next 5 run dates.',
    href: '/tools/cron-builder',
    icon: 'CRON',
    tags: ['dev'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'sql-formatter',
    label: 'SQL Formatter',
    description: 'Format and prettify SQL queries. Keyword capitalization and proper indentation.',
    href: '/tools/sql-formatter',
    icon: 'SQL',
    tags: ['dev'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'color-converter',
    label: 'Color Converter',
    description: 'Convert colors between HEX, RGB, HSL, and HSV with a live preview swatch.',
    href: '/tools/color-converter',
    icon: 'CLR',
    tags: ['design', 'dev'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
  {
    id: 'password-generator',
    label: 'Password Generator',
    description: 'Generate strong passwords with length slider and character set options. Uses crypto.getRandomValues().',
    href: '/tools/password-generator',
    icon: 'PWD',
    tags: ['dev'],
    status: 'live',
    clientOnly: true,
    isNew: true,
  },
];
